name: Build Android APK


# 👇 TAMBAHKAN INI - WAJIB ADA!
on:
  push:                    # Jalan otomatis saat ada push ke branch tertentu
    branches: [ "main", "master" ]
  
  pull_request:            # Jalan saat ada pull request (opsional)
    branches: [ "main" ]
  
  workflow_dispatch:       # Bisa dijalankan manual dari tab Actions


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix permission
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
